export const books = [
    {
      id: '1',
      title: 'It Ends With Us',
      author: 'Colleen Hoover',
      date: '02/08/2016',
      image: require('@/assets/images/book1.jpg'),
      description: 'Un roman poignant sur l’amour, la résilience et le choix difficile entre le passé et le présent.',
    },
    {
      id: '2',
      title: 'The Cottage',
      author: 'Danielle Steel',
      date: '01/04/2002',
      image: require('@/assets/images/book3.jpg'),
      description: 'Une histoire captivante de nouvelles amitiés, de défis et de renaissance dans une villa luxueuse.',
    },
    {
      id: '3',
      title: 'Atomic Habits',
      author: 'James Clear',
      date: '18/10/2018',
      image: require('@/assets/images/book2.png'),
      description: 'Un guide puissant sur la formation des habitudes pour améliorer sa vie chaque jour.',
    },
    {
      id: '4',
      title: 'React Native: Développement Mobile',
      author: 'Emmanuel Henri',
      date: '12/06/2020',
      image: require('@/assets/images/book4.jpg'),
      description: 'Un livre complet pour apprendre à créer des applications mobiles performantes avec React Native.',
    },
    {
      id: '5',
      title: 'Les Misérables',
      author: 'Victor Hugo',
      date: '03/04/1862',
      image: require('@/assets/images/book5.jpg'),
      description: 'Une épopée sociale et politique suivant Jean Valjean dans une France en mutation.',
    },
    {
      id: '6',
      title: 'Le Petit Prince',
      author: 'Antoine de Saint-Exupéry',
      date: '06/04/1943',
      image: require('@/assets/images/book6.jpg'),
      description: 'Un conte philosophique intemporel sur l’amitié, l’amour et l’essence de la vie.',
    },
    {
      id: '7',
      title: 'The Alchemist',
      author: 'Paulo Coelho',
      date: '14/11/1988',
      image: require('@/assets/images/book7.png'),
      description: 'Un récit inspirant sur la poursuite de ses rêves et la découverte de son destin.',
    },
    {
      id: '8',
      title: 'The 48 Laws of Power',
      author: 'Robert Greene',
      date: '01/09/1998',
      image: require('@/assets/images/book8.jpg'),
      description: 'Un guide sur le pouvoir, la manipulation et les stratégies pour réussir dans la vie.',
    },
    {
      id: '9',
      title: 'Rich Dad Poor Dad',
      author: 'Robert Kiyosaki',
      date: '01/04/1997',
      image: require('@/assets/images/book9.jpg'),
      description: 'Une exploration des différences entre l’éducation financière traditionnelle et celle des riches.',
    },
    {
      id: '10',
      title: 'Deep Work',
      author: 'Cal Newport',
      date: '05/01/2016',
      image: require('@/assets/images/book10.jpg'),
      description: 'Un livre essentiel sur la concentration profonde et la productivité à l’ère du numérique.',
    },
  ];
  